### ISSUE TITLE
0.75.1 PowerToys Breaks the Lorem plugin

### ISSUE THREAD

**Issue by artistro08** [dandn9/prun-lorem#1] opened 2023-11-07 00:25 UTC
Exactly what the title says. Not sure what is broken but it simply doesn't start with Powertoys Run

**Comment by aymaneDotenv** [comment] 2023-11-07 15:34
Hi Do you have an M1 Mac 
because I am having the same issue on M2 Mac.
![dye318nrz7c91](https://github.com/dandn9/prun-lorem/assets/131325831/e15401e1-ac63-4b52-8bb3-7e6c85533abc)

**Comment by lucs100** [comment] 2024-01-15 02:48
Bump. Getting a "Fail to initialize plugins" error when I start PowerToys Run. When I start Run with Lorem disabled I get this error: 
![image](https://github.com/dandn9/prun-lorem/assets/59773132/9e598f12-5ca9-4869-939a-592ad17094cf)
Couldn't find a log file from PowerToys but can look for one if it helps.

Edit: Found logs a few minutes after posting this (you need to press "bug report" on the PowerToys tray icon then wait for logs to be dropped on your desktop).

Seems to be caused by a missing PluginID:

> [2024-01-14 21:47:49.5459] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::199]
Can't validate plugin ID of plugin <Lorem> in C:\Program Files\PowerToys\RunPlugins\Lorem\Lorem.dll: The static property <Main.PluginID> was not found.

Referencing off a couple other plugins it looks like `public static string PluginID => "EF2F634F20484459A365944EE7B07121";`  (GUID comes from plugin.json in this project) will need to be dropped onto line 15 of [src/Lorem/Main.cs](https://github.com/dandn9/prun-lorem/blob/main/src/Lorem/Main.cs).

**Comment by lucs100** [comment] 2024-01-15 02:52
Found logs a few minutes after posting this (you need to press "bug report" on the PowerToys tray icon then wait for logs to be dropped on your desktop).

Seems to be caused by a missing PluginID:

> [2024-01-14 21:47:49.5459] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::199]
Can't validate plugin ID of plugin <Lorem> in C:\Program Files\PowerToys\RunPlugins\Lorem\Lorem.dll: The static property <Main.PluginID> was not found.

**Comment by dandn9** [comment] 2024-01-15 11:19
Heyall ^^ thanks for letting me know; it should be fixed now with the new release

**Closed as completed by dandn9** 2024-01-15 11:19 UTC

**Comment by lucs100** [comment] 2024-01-15 21:49
Can confirm it works perfectly now, thank you!!

**Comment by artistro08** [comment] 2024-01-16 17:20
Thanks man!
